### ISSUE TITLE
Cannot graph numbers larger than 1e308

### ISSUE THREAD

**Issue by dfederm** [dfederm/ClickerHeroesTracker#113]
Highcharts can't handle non-numbers like the Decimal lib we're using. For now, we detect this and just show an error in place of the graph.

A possible solution is to manually take the log and graph linearly.

Split off from #59

**Comment by valepakh** [comment]
Doesn't seem to be fixed actually, am I missing something?
Maybe there's some kind of placeholder?
All I see is

> This graph contains values which are currently too large to graph.
> This will be fixed soon.

**Comment by dfederm** [comment]
@valepakh I'm actually working on rewriting the site as an Angular app (#109) and this bug is only fixed there. I'll reopen the issue for clarity and re-close it once the Angular app ships.

**Comment by dfederm** [comment]
Closing as this should work on the new site which is almost ready (and there's a banner on the old site now for the new one).
