### ISSUE TITLE
Avoid suggestions for ancients not yet summoned

### ISSUE THREAD

**Issue by dfederm** [dfederm/ClickerHeroesTracker#156]

**Comment by koutoftimer** [comment]
I'm not sure it is actually a bug. Because somebody could not know how useful some of the ancients can be.

**Comment by dfederm** [comment]
It would be an optional setting users could turn on and off

**Comment by dfederm** [comment]
Not worrying about this. It's really only useful for really early game, where the ancient suggestions really shouldn't be used religiously regardless.
