### ISSUE TITLE
What is the post limitation for anonymous?

### ISSUE THREAD

**Issue by koutoftimer** [dfederm/ClickerHeroesTracker#225]
I had this error `POST https://dc.services.visualstudio.com/v2/track 439 (Daily quota exceeded)` during upload. Didn't get it, why browser makes such request, Is it necessary?

**Comment by dfederm** [comment]
That's an application insights (telemetry) call. The reason you're seeing a quota exceeded message is because I'm using the free tier which runs out pretty quickly.
