### ISSUE TITLE
Savegame generation stopped working a couple days ago

### ISSUE THREAD

**Issue by igorfraa** [dfederm/ClickerHeroesTracker#232]
The subject. 

Not working also for older saves for which it used to.

**Comment by dfederm** [comment]
@igorfraa can you elaborate? My calculator doesn't have an autoleveler if that's what you're referring to. I'm tracking that with #102. If you mean that the save game fails to parse, please provide an example.

**Comment by igorfraa** [comment]
the checkbox "Enable save-game generation" and
"This experimental functionality is considered cheating. Always backup your original save-game. If you notice problems, please notify me as soon as possible." 

Did I missed the repo? :)

**Comment by dfederm** [comment]
@igorfraa I think you have the wrong repo. This is https://clickerheroestracker.azurewebsites.net/

**Comment by igorfraa** [comment]
@dfederm so sorry for wrong ticket :)

**Comment by igorfraa** [comment]
@dfederm 
but suggestions for Outsiders https://clickerheroestracker.azurewebsites.net/  are really wrong.

for my 3.5k ancient souls I really don't need for 26lvl Borb (13lvl brings much more then my cap) or 18lvl Sen-Akhan (4lvl enough ) and 10lvl K'Ariqua is VERY low (35-40lvl is good)
