### ISSUE TITLE
Add option to leave souls in the bank for regilds

### ISSUE THREAD

**Issue by dfederm** [dfederm/ClickerHeroesTracker#32]

**Comment by oshman6785** [comment]
+1

And an easy way to turn on and off. 
And an option to define how many full regild moves you want to reserve.

For example, I may move two or three times to see who gives me the better DPS (i.e. when at that break point between Wep boosting Betty / Midas / or himself).

**Comment by dfederm** [comment]
Not worrying about this feature. This really only applies to very early game (like < 1e6 souls), where the ancient suggestions shouldn't be religiously followed anyway.
