### ISSUE TITLE
Incorrect display of Transcendent Power in graphs

### ISSUE THREAD

**Issue by VADemon** [dfederm/ClickerHeroesTracker#364]
Save: `https://clickerheroestracker.azurewebsites.net/uploads/1556436`

Under Misc.: `Transcendent Power | 25.0%`

The game shows `24.99%` instead on the current save. Screenshot as proof:

![2020 05 05_16-55-08__Clicker Heroes](https://user-images.githubusercontent.com/1168140/81080678-4f7bd700-8ef1-11ea-8eb9-9aca73bbeb8f.png)
✔

**Comment by dfederm** [comment]
Your actual TP is: 24.99999999999895%. The game and the calculator are just rounding differently.

**Comment by VADemon** [comment]
> 24.99999999999895%

LOL. If only I knew. You can close this as minor then.

Shouldn't the website try to be more in line with how the game shows it? Though it could be a bit nasty to fix:

- string format with 2 decimal points: %.2f?
- if that doesn't work: *100, IEEE754 round towards zero/-inf, /100

**Comment by dfederm** [comment]
I'd actually argue that the intent of the website (and any calculator for the game) is to show numbers the game doesn't show, and/or show them at greater precision.
